language: node_js
node_js:
  - "6"
  - "5"
before_install:
  #- export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
install:
  - npm install
  - npm run compile:tsc # compile all the filesa
  - cd demo/
  - npm install
  - node_modules/.bin/ng build
  - |
    node_modules/.bin/ng serve &
    SERVER_PID=$!
  - echo $SERVER_PID
  - sleep 10 # give the server a jump start
  - cd ../
script:
  - npm test
after_script:
  - kill $SERVER_PID
